import { ScanResult, PackageAnalysis } from '@/types';
import { config } from '@/lib/config';

// ---- JSON Export ----

export function exportToJSON(result: ScanResult): void {
  const data = JSON.stringify(result, null, 2);
  downloadFile(data, `deadware-scan-${result.id.slice(0, 8)}.json`, 'application/json');
}

// ---- PDF Export (HTML-based print) ----

export function exportToPDF(result: ScanResult): void {
  const html = generatePDFHtml(result);
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}

function generatePDFHtml(result: ScanResult): string {
  const riskColor = (level: string) => {
    switch (level) {
      case 'critical': return '#ef4444';
      case 'high': return '#f97316';
      case 'medium': return '#eab308';
      case 'low': return '#22c55e';
      case 'healthy': return '#10b981';
      default: return '#6b7280';
    }
  };

  const packageRows = result.packages
    .sort((a, b) => b.risk.overall - a.risk.overall)
    .map((p: PackageAnalysis) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;">${p.package.name}${p.signals.deprecated ? ' <span style="color:#ef4444;font-size:11px;">[DEPRECATED]</span>' : ''}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;">${p.package.version}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;color:${riskColor(p.risk.level)};font-weight:600;">${p.risk.overall}/100 (${p.risk.level.toUpperCase()})</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;">${p.signals.daysSinceLastRelease ?? 'N/A'} days</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;">${p.signals.vulnerabilities.length > 0 ? `<span style="color:#ef4444;font-weight:600;">${p.signals.vulnerabilities.length}</span>` : '0'}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;">${p.replacements.length > 0 ? p.replacements.map(r => r.name).join(', ') : '—'}</td>
      </tr>
    `).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <title>Deadware Risk Report — ${new Date(result.createdAt).toLocaleDateString()}</title>
  <style>
    body{font-family:system-ui,-apple-system,sans-serif;margin:40px;color:#1f2937;}
    h1{font-size:24px;margin-bottom:4px;}
    .subtitle{color:#6b7280;margin-bottom:24px;}
    .summary{display:flex;gap:16px;margin-bottom:32px;}
    .stat{padding:16px;border-radius:8px;background:#f9fafb;border:1px solid #e5e7eb;min-width:100px;}
    .stat-value{font-size:28px;font-weight:700;}
    .stat-label{font-size:12px;color:#6b7280;text-transform:uppercase;}
    table{width:100%;border-collapse:collapse;font-size:14px;}
    th{text-align:left;padding:8px;border-bottom:2px solid #1f2937;font-size:12px;text-transform:uppercase;color:#6b7280;}
    .footer{margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;}
  </style>
</head>
<body>
  <h1>Deadware Risk Report</h1>
  <p class="subtitle">Generated ${new Date(result.createdAt).toLocaleString()} &bull; ${result.summary.totalPackages} packages scanned &bull; ${result.ecosystem.toUpperCase()}</p>

  <div class="summary">
    <div class="stat">
      <div class="stat-value" style="color:${result.summary.overallHealthScore >= 70 ? '#10b981' : result.summary.overallHealthScore >= 40 ? '#eab308' : '#ef4444'}">${result.summary.overallHealthScore}</div>
      <div class="stat-label">Health Score</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#ef4444">${result.summary.critical}</div>
      <div class="stat-label">Critical</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#f97316">${result.summary.high}</div>
      <div class="stat-label">High</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#eab308">${result.summary.medium}</div>
      <div class="stat-label">Medium</div>
    </div>
    <div class="stat">
      <div class="stat-value" style="color:#22c55e">${result.summary.low + result.summary.healthy}</div>
      <div class="stat-label">Low/Healthy</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Package</th>
        <th>Version</th>
        <th>Risk Score</th>
        <th>Last Release</th>
        <th>Vulns</th>
        <th>Replacements</th>
      </tr>
    </thead>
    <tbody>
      ${packageRows}
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by Deadware Risk Scanner &bull; ${config.siteUrl.replace('https://', '')}</p>
  </div>
</body>
</html>`;
}

// ---- CSV Export ----

export function exportToCSV(result: ScanResult): void {
  const headers = [
    'Package',
    'Version',
    'Ecosystem',
    'Risk Score',
    'Risk Level',
    'Days Since Release',
    'Maintainers',
    'Deprecated',
    'Vulnerabilities',
    'License',
    'Replacements',
  ];

  const rows = result.packages
    .sort((a, b) => b.risk.overall - a.risk.overall)
    .map((p) => [
      csvEscape(p.package.name),
      csvEscape(p.package.version),
      p.package.ecosystem,
      p.risk.overall.toString(),
      p.risk.level.toUpperCase(),
      p.signals.daysSinceLastRelease?.toString() ?? 'N/A',
      p.signals.maintainerCount?.toString() ?? 'N/A',
      p.signals.deprecated ? 'Yes' : 'No',
      p.signals.vulnerabilities.length.toString(),
      csvEscape(p.signals.license ?? 'Unknown'),
      csvEscape(p.replacements.map((r) => r.name).join('; ') || 'None'),
    ]);

  const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  downloadFile(csv, `deadware-scan-${result.id.slice(0, 8)}.csv`, 'text/csv');
}

function csvEscape(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

// ---- CI Badge ----

export function generateBadgeUrl(healthScore: number): string {
  const color = healthScore >= 70 ? 'brightgreen' : healthScore >= 40 ? 'yellow' : 'red';
  const label = encodeURIComponent('deadware risk');
  const message = encodeURIComponent(`${healthScore}/100`);
  return `https://img.shields.io/badge/${label}-${message}-${color}`;
}

export function generateBadgeMarkdown(healthScore: number): string {
  const url = generateBadgeUrl(healthScore);
  return `[![Deadware Risk Score](${url})](${config.siteUrl})`;
}

// ---- Helpers ----

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
